# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Body', models.TextField()),
                ('Tag', models.CharField(max_length=5000)),
            ],
        ),
    ]
