# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WriteReview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='author',
            field=models.CharField(default='srihari unnikrishnan', max_length=5000),
            preserve_default=False,
        ),
    ]
