# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WriteReview', '0002_reviews_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.CharField(max_length=5000)),
                ('Author', models.CharField(max_length=5000)),
                ('alive', models.BooleanField(default=True)),
            ],
        ),
    ]
