# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-30 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WriteReview', '0003_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=10000)),
                ('user', models.CharField(max_length=5000)),
                ('article', models.CharField(max_length=100000000)),
            ],
        ),
    ]
