# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-05 16:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('WriteReview', '0005_auto_20171001_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='published',
            field=models.DateField(default=datetime.datetime(2017, 10, 5, 16, 11, 20, 692113, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviews',
            name='views',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
